import { ProtectedLayout } from "@/components/Layout";
import { trpc } from "@/providers/trpc";
import { useAuth } from "@/hooks/useAuth";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  FileText,
  Download,
  Sparkles,
  Loader2,
  FileDown,
} from "lucide-react";

export default function Reports() {
  const { user } = useAuth();
  const [searchTerm, setSearchTerm] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedReport, setGeneratedReport] = useState("");

  const reportMutation = trpc.analysis.generateReport.useMutation();

  // Demo: generate a report on demand
  const handleGenerateReport = async () => {
    if (!searchTerm) return;
    setIsGenerating(true);
    try {
      const result = await reportMutation.mutateAsync({
        title: searchTerm,
        asin: `DEMO-${Date.now()}`,
        analysis: `Demo analysis for ${searchTerm}`,
        scores: {
          totalScore: 85,
          grade: "B",
          recommendation: "সতর্কতা (CAUTION) — ঝুঁকি আছে কিন্তু সুযোগও আছে",
        },
      });
      setGeneratedReport(result.report);
    } catch (error) {
      console.error(error);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleExportPDF = () => {
    if (!generatedReport) return;

    // Create a formatted HTML for PDF
    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <title>Amazon FBA Research Report</title>
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Noto+Sans+Bengali:wght@400;600;700&display=swap');
          body {
            font-family: 'Noto Sans Bengali', sans-serif;
            padding: 40px;
            max-width: 800px;
            margin: 0 auto;
            color: #333;
            line-height: 1.8;
          }
          h1 { color: #1e40af; border-bottom: 3px solid #3b82f6; padding-bottom: 10px; }
          h2 { color: #1e40af; margin-top: 30px; }
          .header { text-align: center; margin-bottom: 40px; }
          .meta { background: #f0f7ff; padding: 15px; border-radius: 8px; margin-bottom: 30px; }
          .footer { margin-top: 50px; padding-top: 20px; border-top: 1px solid #ddd; text-align: center; color: #666; font-size: 12px; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>Amazon FBA Research Report</h1>
          <p>Generated by FBA AI Research Platform</p>
        </div>
        <div class="meta">
          <strong>Date:</strong> ${new Date().toLocaleDateString("en-US")}<br>
          <strong>User:</strong> ${user?.name || "N/A"}<br>
          <strong>Product:</strong> ${searchTerm}
        </div>
        <div>${generatedReport.replace(/\n/g, "<br>")}</div>
        <div class="footer">
          <p>© 2026 FBA AI Research Platform | Built for Bangladeshi Entrepreneurs</p>
        </div>
      </body>
      </html>
    `;

    const blob = new Blob([htmlContent], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `fba-research-report-${Date.now()}.html`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <ProtectedLayout>
      <div className="space-y-8 max-w-5xl mx-auto">
        {/* Header */}
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
          <div>
            <h1 className="text-3xl font-bold text-slate-900 dark:text-white">
              রিসার্চ রিপোর্টস
            </h1>
            <p className="text-slate-500 dark:text-slate-400 mt-1">
              AI-জেনারেটেড বাংলা রিপোর্ট দেখুন ও এক্সপোর্ট করুন
            </p>
          </div>
        </div>

        {/* Generate Report Section */}
        <Card className="border-0 shadow-xl">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Sparkles className="h-5 w-5 text-blue-600" />
              নতুন রিপোর্ট জেনারেট করুন
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="flex gap-4">
              <Input
                placeholder="প্রোডাক্ট টাইটেল বা কীওয়ার্ড দিন..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="h-12 rounded-xl flex-1"
              />
              <Button
                onClick={handleGenerateReport}
                disabled={isGenerating || !searchTerm}
                className="h-12 px-6 rounded-xl bg-gradient-to-r from-blue-600 to-purple-600"
              >
                {isGenerating ? (
                  <Loader2 className="h-5 w-5 mr-2 animate-spin" />
                ) : (
                  <Sparkles className="h-5 w-5 mr-2" />
                )}
                জেনারেট
              </Button>
            </div>
          </CardContent>
        </Card>

        {/* Report Display */}
        {generatedReport && (
          <Card className="border-0 shadow-xl">
            <CardHeader className="flex flex-row items-center justify-between">
              <CardTitle className="flex items-center gap-2">
                <FileText className="h-5 w-5 text-purple-600" />
                রিপোর্ট: {searchTerm}
              </CardTitle>
              <Button
                onClick={handleExportPDF}
                variant="outline"
                className="rounded-xl"
              >
                <FileDown className="h-4 w-4 mr-2" />
                HTML এক্সপোর্ট
              </Button>
            </CardHeader>
            <CardContent>
              <div className="prose dark:prose-invert max-w-none">
                <div className="whitespace-pre-wrap text-slate-700 dark:text-slate-300 leading-relaxed bg-slate-50 dark:bg-slate-800 p-6 rounded-xl">
                  {generatedReport}
                </div>
              </div>
            </CardContent>
          </Card>
        )}

        {/* Instructions */}
        {!generatedReport && (
          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {[
              {
                icon: FileText,
                title: "বাংলা রিপোর্ট",
                desc: "AI সম্পূর্ণ বাংলায় বিস্তারিত রিপোর্ট তৈরি করে",
                color: "from-blue-400 to-blue-600",
              },
              {
                icon: Download,
                title: "HTML এক্সপোর্ট",
                desc: "রিপোর্ট HTML হিসেবে ডাউনলোড করুন",
                color: "from-green-400 to-green-600",
              },
              {
                icon: Sparkles,
                title: "AI-জেনারেটেড",
                desc: "Kimi AI প্রযুক্তি ব্যবহার করে স্মার্ট রিপোর্ট",
                color: "from-purple-400 to-purple-600",
              },
            ].map((item) => {
              const Icon = item.icon;
              return (
                <Card
                  key={item.title}
                  className="border-0 shadow-lg hover:shadow-xl transition-all"
                >
                  <CardContent className="p-6">
                    <div
                      className={`w-12 h-12 bg-gradient-to-br ${item.color} rounded-xl flex items-center justify-center mb-4`}
                    >
                      <Icon className="h-6 w-6 text-white" />
                    </div>
                    <h3 className="font-bold text-slate-800 dark:text-white mb-2">
                      {item.title}
                    </h3>
                    <p className="text-sm text-slate-500 dark:text-slate-400">
                      {item.desc}
                    </p>
                  </CardContent>
                </Card>
              );
            })}
          </div>
        )}
      </div>
    </ProtectedLayout>
  );
}
